apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: database
  name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: local-path