---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: memos
  namespace: memos
spec:
  encryptedData:
    MEMOS_DSN: AgCyP5YNIoSfLX/NkcaduA88i4ZE8i4oT0u1SGDwaqhflknzR0vm8UeaGFrKj32YsNNZ+L1KmR/USRvC6jU7kCjNBQesBw4seAMRbHvCtmNadfiKBG8rhPYc9w5wv68WGbbNGGQoZd7YLw/VaeXuBXoNh9YiuikbPKfBL6G+SJGpvWl88XP/mKsuuJoGayIKpe8DdGS87Q6cuoiBT9Zx1j6sVRbZOcJhGrLEypFt6n8pAmlxj4Yo+l2fQDfADsi2vLP/y9WwtZYsEGuWao7XHvdiD3ZPjmYWFBrZOI4ptEruu+PX7mxijHueV2oZj/IgAs6Vmvg+zaU1jqrkqGCoyfxT1ijXSrSyIBbidMYdHT1haV/ai6Vocd9ca3zdCqTsIYx4kVjSPuNPiJfG+NpxBqGGHVbJyLwFwqI75xdW+WiBEqlJQ++UKonw+AsXY7OT5eI0ccGAsPtVn/FR60YuWfHtH52UqcMDOLXkBWtduLfWQGMqKJgeQ/ok0TVzCOWPbSczhyxcvuzqCsjonaz/f+8e7rGEMW4L5Hi0OHXWnbdb3wJSZbHXXWNVEO3J5PXD3V7VukKLud83ehszrdGhD6BdIZWx5/z0eCm95rEPBFpBob+telLsPuTx/qHQ1Cd2K00vbbR8g48RTaiw6epgxzD+Icmyft0G7EhJDe+uQT3wP1euESc9jeF0xNk2KyK2roHMUwLeJRHKdWstKSGSom6xDErT0+EOBRcl0fBRoh04iCLTtbaKd6UdO+ZXEchWGVOayYV5g8ZB3evgTVuQ9SW4yaDQXi23DP5eyxxztw5BW3oXPBPWtyA/OBynYV66Dv3bk/igqVjKDR02zc1N8FkDry+wR0/TaF9KHcstIiw=
  template:
    metadata:
      name: memos
      namespace: memos
    type: Opaque
