---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: memos
  namespace: memos
spec:
  encryptedData:
    MEMOS_DSN: AgAXpDG9EP0DZ0WDmcAGiXkKEwexF2y9J90L8AzQqbi+jeHZFlEMFWBSC10eYiHsekTwKjx5cr4FoXG14LOrCD6QOr65IBEv2UGNFv7ZLA9S014nI9kBSLs4eU/9p3pdg/lHvGGDxHG8gqNuMJmhskT/9bdI2013IwUgezt/FX87COsgF3y6Kj4sM4AOdDZ6Ck6tSpXtigfknMrWHTbYyZtGp4y+52ZUy3lR1KKxWHjCVjvmvZUOogLzQm5WqtQzmEGvEDvTIWu3QNdkc7W837DDzNoeKfTBzszy51hmnPC8HfTLFSWDZWfygfG3HYnbmkqTR3cgosrzRkpeARcA94gntQKtHzOeSi8vxw9TWo4wS4DTJWUWLFXRT/bjew0CBkevkqgmbRtR3ws9XdMGw5iqFpaNF3uPqw+2Wi25nOPdlrj3I/s1p5EjWyE7zG6SQl4ySA48Qg3FqHM2XNan6TCbpDXoCvN+z/sVmL+V8i1k/KbKymtdhcNpDy+vdYQWsTRTEvpiSgJJdLaIfkfJXsLoRE4ngCTDFLZJhsm8C8ltdqJidV1koIMZX/5l8e8sOthxEUQYZrtxsCumfvYk918Dt2xzWelWy56PmJ0tchyW0cu9WxO7rKFf+cVuBkU+oASb63MY0NWngCEzDw2+LtaYxJvpwht6rFp42k1yYpd0LqwzNwZhuSjfsD2gtXBgqHM27n56cxh2IpnCYjSSAramy3NM7ZXiAmLrQOo28u65Q6rNYTtXLAVkV91s6ZzeTG8UtufJLMSvKD+SVMBarym8FvgzUkaobI1oGGBB+NWBXg32RXwhAVoe2iW0K21xBOPllQLrOsITAZP053UicX8bmtNB7gN3zypgbdozYOQ=
  template:
    metadata:
      name: memos
      namespace: memos
    type: Opaque
