---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: memos
  namespace: memos
spec:
  encryptedData:
    MEMOS_DSN: AgAxkB2b6g4buK0gQSDJ6eR4KDAfNaknBNasa+HCJRBRu4Oyk06D8P0mRRL3OBmo349hzuM0KKmcvTmEdT7OlaBDLzPw6YhANN9JQJ42uIEYAFn+O+YBAtluBh3SzLXLK+w97sEIFg2NnLqfyGnwwW7dwlW7tGENnW7hDzVIZDucfK9esSWbTN9ha09dUI/eLLpqGyascT4h+yzFsm0c+5hmdj7cWJxo+PL5uS1TdNCJ5mXn2e88QV9kXbvv8im1cLu4HBJWp9WQdv4lahmGEYKqTuYXv/4z+v8e+fqb78ttcyLGJ9Bs9VVCRNBReLVYj8cAF9fbIGYz0Kr4eyULqX6ahU6oiDkIp3Hxc10mWfh734KI+EbU7OsFX90gIi+X8j1joG8bOffjJbedfcaxb48agq10eXHPZavGC0xWep1W1S3J2ZdbhuIeAY9/grgz2DQEf0w9Rh/i4wj8YnFHpj1EBu2vYyEinQ4NIXSCWQyayklM6re7OauIrSfdWeE2XK9jj5ApaojkpS+qiwilkNNS0ROmL9kvfsolVkKz/6ms0WaDMTvmPa2hRQdFiQw6pB2iRDrVniRQnX0bWNDFX/Iu+CO97ekNjdbgK+X/FANJ69+Abl/HUlMZKYNzyIFQXSSAxDRLNaedrfex5on1W3fBSXlGa9GjdrsotUmSqBFW8etRQUP1hMvQaR4jz61pvT/jA4PFtaDBmTNx9uTV+oWhBZc8/UWKNwIwCNwdiOdtLaInYb8wbo8TdyJMbGdWq58vQp4QkzN4ZX5wXfC6lhWYRByi8kbwONRNtgHo3hpZ2W2LPkBEd5UsHJl6ThVrU+b3cicLy2AIED1uazaTO7rDkAsUO8wpdWWiMTJOOd8=
  template:
    metadata:
      name: memos
      namespace: memos
    type: Opaque
