---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres
  namespace: database
spec:
  encryptedData:
    password: AgAu+jFDY51jzNZhoU7rI16M387AyDaSjSOq6/Bnypyf+nhjvjFaNqCgiylacKQVCefHAtxe5OOZ1TNxfnYTxceD0hP57OoC3OZAe2fBnYoEk18A74NTat+HH6xVwKPn3MtsPaWqk7oFCTKExMGzjVvpIdBa4G5puN7UVpUs5ivZaIQ/AVD1jniWinqj90rTAdfg2BHf0YBPpbJJcA/9eNXfLDYIg8NnoGmKY4igiiu2KjmxukqkBt4FoIHgmzBn0lfngAoNOv4yFyaaQBGDBZeTVQ7HUQXgZ2cxQjORWbHnobttLn/X2wDNPXn0V6hUoiAlso7ewbCiDNMWsGyeHm/Tr7P2DE74jtfKhWypGMPTmx/2yR9bcwqfspqtm+LNDZoXX5x7oSqYg672wtYPi75eyj78zYtPxdADGmoY5TjNWsG7lHHUIG0g8y+Wek+l6HJjTVnX4SbCAUw/TFKFIkTZOg6nlW+AB1cOJqdI937gBhufxGabifs+7XMUtObJErPORSBZharcuiBCJko6eVaMyqBcE06UteEasZxaPN/iax1XSw45w5UaWiLgKP5YCLjHZBSv4afFSvsv9oMtL1s9gkm+QG15fQiMqV5DNYVf2LdQpy9TIT5f6ymXXs+JnNbeF4pBV37e8ziynwuo/7GuDO3xKvffNlkkZL0qCJ8/BfctvGAQ2pFREJ9gc14/eFTOB+PD68T5ebXIyl8LLbVMRSwYkbgz/P+2NkZL3LPWeTWikkcP0xq27JssSg==
  template:
    metadata:
      name: postgres
      namespace: database
